name = "snowflare-for-remote-signer"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"

[durable_objects]
bindings = [
  { class_name = "Relay", name = "RELAY" },
]

[[migrations]]
new_sqlite_classes = ["Relay"]
tag = "v1"

[[kv_namespaces]]
binding = "events"
id = "%KV_ID_EVENTS%"

[[kv_namespaces]]
binding = "accounts"
id = "%KV_ID_ACCOUNTS%"

[[d1_databases]]
binding = "DB"
database_name = "snowflare-events"
database_id = "%DB_ID%"

[observability]
enabled = true
head_sampling_rate = 1
