name = "snowflare-for-remote-signer"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"

[durable_objects]
bindings = [
  { class_name = "Relay", name = "RELAY" },
]

[[migrations]]
new_sqlite_classes = ["Relay"]
tag = "v1"

[observability]
enabled = true
head_sampling_rate = 1
